In [48]:
import pandas as pd

url1 = "heart_stroke_train_dataset.csv"
url2 = "heart_stroke_test_dataset.csv"

train_df = pd.read_csv(url1)
test_df = pd.read_csv(url2)

In [49]:
train_df.head()

,ID,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,846,Female,48.0,0,0,Yes,Private,Urban,69.21,33.1,never smoked,0
1,3745,Male,15.0,0,0,No,Private,Rural,122.25,21.0,never smoked,0
2,4184,Female,67.0,0,0,Yes,Self-employed,Rural,110.42,24.9,never smoked,0
3,3410,Male,44.0,0,0,Yes,Private,Urban,65.41,24.8,smokes,0
4,285,Male,14.0,0,0,No,Govt_job,Urban,82.34,31.6,Unknown,0

In [50]:
print(train_df.shape)
print(test_df.shape)

(4088, 12)
(1022, 11)

In [51]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4088 entries, 0 to 4087
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 4088 non-null   int64
 1   gender             4088 non-null   object
 2   age                4088 non-null   float64
 3   hypertension       4088 non-null   int64
 4   heart_disease      4088 non-null   int64
 5   ever_married       4088 non-null   object
 6   work_type          4088 non-null   object
 7   Residence_type     4088 non-null   object
 8   avg_glucose_level  4088 non-null   float64
 9   bmi                3918 non-null   float64
 10  smoking_status     4088 non-null   object
 11  stroke             4088 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 383.4+ KB

In [52]:
train_df.describe()

,ID,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,4088.000000,4088.000000,4088.000000,4088.000000,4088.000000,3918.000000,4088.000000
mean,2539.784002,43.353288,0.097114,0.054061,106.317167,28.922180,0.048679
std,1484.069131,22.596816,0.296148,0.226165,45.259652,7.928378,0.215223
min,1.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,1250.750000,26.000000,0.000000,0.000000,77.312500,23.600000,0.000000
50%,2525.000000,45.000000,0.000000,0.000000,91.945000,28.000000,0.000000
75%,3844.250000,61.000000,0.000000,0.000000,114.197500,33.100000,0.000000
max,5110.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [53]:

train_df.isna().sum()

ID                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  170
smoking_status         0
stroke                 0
dtype: int64

In [54]:
print(train_df.isna().sum()/len(train_df))

ID                   0.000000
gender               0.000000
age                  0.000000
hypertension         0.000000
heart_disease        0.000000
ever_married         0.000000
work_type            0.000000
Residence_type       0.000000
avg_glucose_level    0.000000
bmi                  0.041585
smoking_status       0.000000
stroke               0.000000
dtype: float64

In [55]:
df=train_df.drop_duplicates(keep=False)
print(df.shape) #no duplicates found

(4088, 12)

Median Imputation on BMI

In [56]:

train_df['bmi'] = train_df['bmi'].fillna(train_df['bmi'].median())
test_df['bmi'] = test_df['bmi'].fillna(train_df['bmi'].median())

Encoding

In [57]:

train_df_en = pd.get_dummies(train_df,drop_first=True)

print(train_df_en.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4088 entries, 0 to 4087
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              4088 non-null   int64
 1   age                             4088 non-null   float64
 2   hypertension                    4088 non-null   int64
 3   heart_disease                   4088 non-null   int64
 4   avg_glucose_level               4088 non-null   float64
 5   bmi                             4088 non-null   float64
 6   stroke                          4088 non-null   int64
 7   gender_Male                     4088 non-null   bool
 8   gender_Other                    4088 non-null   bool
 9   ever_married_Yes                4088 non-null   bool
 10  work_type_Never_worked          4088 non-null   bool
 11  work_type_Private               4088 non-null   bool
 12  work_type_Self-employed         4088 non-null   bool
 13  work_type_children              4088 non-null   bool
 14  Residence_type_Urban            4088 non-null   bool
 15  smoking_status_formerly smoked  4088 non-null   bool
 16  smoking_status_never smoked     4088 non-null   bool
 17  smoking_status_smokes           4088 non-null   bool
dtypes: bool(11), float64(3), int64(4)
memory usage: 267.6 KB
None

In [58]:

from sklearn.model_selection import train_test_split



X = train_df_en.drop(columns=['stroke','ID'],axis=1)
y = train_df_en['stroke']

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3270, 16), (818, 16), (3270,), (818,))

In [59]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)

X_test_scaler = scaler.transform(X_test)

Train model

In [60]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver = "liblinear",random_state=42,max_iter=1000,class_weight="balanced")
log_reg.fit(X_train_scaler,y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42,
                   solver='liblinear')

After adding class_weigt="balanced",Increasing the penalty for the minority class makes the optimizer treat those errors as more costly. As a result, the model shifts its decision boundary to predict more minority-class samples, which usually increases recall for stroke cases at the expense of some additional false positives and lower overall accuracy

In [61]:

y_pred = log_reg.predict(X_test_scaler)

In [62]:

log_reg.intercept_

array([-1.17952987])

In [63]:
log_reg.classes_

array([0, 1], dtype=int64)

In [64]:
log_reg.intercept_

array([-1.17952987])

In [65]:

log_reg.coef_

array([[ 1.99636634,  0.17869742,  0.04356026,  0.13346124,  0.16118044,
        -0.00429961, -0.05519225, -0.12185116, -0.15373393, -0.05097454,
        -0.17286587,  0.43511843,  0.11848728, -0.01007608, -0.13987362,
         0.13134386]])

In [80]:
#Predict probabilities for the positive class (class 1)
y_prob = log_reg.predict_proba(X_test_scaler)[:,1]
y_prob

array([0.77494635, 0.02144844, 0.02791305, 0.91589219, 0.74225311,
       0.29463864, 0.4535415 , 0.59255136, 0.47835057, 0.03508881,
       0.10419694, 0.05246965, 0.82218233, 0.95248126, 0.03338525,
       0.11323002, 0.56263479, 0.03088874, 0.62234629, 0.10880021,
       0.04211541, 0.08241656, 0.51003015, 0.40242619, 0.14816794,
       0.26504322, 0.09744636, 0.04642755, 0.81579524, 0.8199554 ,
       0.10739182, 0.14894713, 0.08590799, 0.55822058, 0.06630812,
       0.88533766, 0.02915222, 0.85872548, 0.47249579, 0.54270069,
       0.75262558, 0.26724296, 0.32623621, 0.08009835, 0.05239106,
       0.84010852, 0.07574342, 0.9146952 , 0.61942649, 0.5863453 ,
       0.01959017, 0.06863401, 0.0420017 , 0.50291737, 0.67142511,
       0.59093601, 0.05545934, 0.65066477, 0.03784436, 0.18240864,
       0.06263611, 0.02784567, 0.78774457, 0.29305453, 0.06926193,
       0.04058863, 0.66172837, 0.02350931, 0.77966311, 0.07933912,
       0.84480292, 0.26365245, 0.77424644, 0.87368642, 0.91247734,
       0.03416279, 0.52110762, 0.9248047 , 0.76692242, 0.03530793,
       0.85149718, 0.11579396, 0.21122513, 0.80497641, 0.75170182,
       0.46951283, 0.02912676, 0.77864237, 0.73033752, 0.02885276,
       0.34839982, 0.02118127, 0.04250908, 0.03997964, 0.1781579 ,
       0.2751256 , 0.28389056, 0.0825303 , 0.02964758, 0.06303704,
       0.10545082, 0.42108844, 0.05265555, 0.42207288, 0.77558306,
       0.50841215, 0.32205302, 0.35434119, 0.24765093, 0.05772192,
       0.17673207, 0.0367601 , 0.46527738, 0.07768829, 0.06755267,
       0.52903223, 0.03177517, 0.50563637, 0.02380831, 0.08672938,
       0.81084636, 0.83823143, 0.33212241, 0.02469024, 0.01086369,
       0.425815  , 0.70510883, 0.01699428, 0.52260067, 0.32632586,
       0.78314878, 0.36644538, 0.50515326, 0.75579251, 0.03953441,
       0.24753617, 0.05759014, 0.01613549, 0.07106965, 0.4635547 ,
       0.09285134, 0.05109275, 0.54743876, 0.03618726, 0.03743439,
       0.04313143, 0.26065685, 0.02227071, 0.08936386, 0.73467693,
       0.80975575, 0.03754449, 0.19957354, 0.31889696, 0.23532161,
       0.04774261, 0.18397529, 0.39522577, 0.62944474, 0.37841039,
       0.07444419, 0.04529053, 0.39999327, 0.02429227, 0.02195899,
       0.89767361, 0.13208235, 0.77166294, 0.3691604 , 0.23651848,
       0.76717339, 0.03833666, 0.0749651 , 0.49189641, 0.03895734,
       0.07767943, 0.71234922, 0.75524546, 0.44571201, 0.02957585,
       0.08738806, 0.22781099, 0.40049276, 0.02566174, 0.07753092,
       0.07310127, 0.63978889, 0.37289157, 0.00284432, 0.03063546,
       0.02605223, 0.31692561, 0.02332363, 0.26856131, 0.10474943,
       0.36111811, 0.02167818, 0.04116554, 0.03971225, 0.15565816,
       0.22331056, 0.04469602, 0.0253987 , 0.05227678, 0.61947391,
       0.57105821, 0.2321435 , 0.03154187, 0.02845363, 0.76442675,
       0.34525456, 0.21160316, 0.36525095, 0.45968081, 0.8466822 ,
       0.04111165, 0.50053054, 0.31080204, 0.03979623, 0.43921144,
       0.76990944, 0.13677447, 0.75368592, 0.34661528, 0.30883733,
       0.08412418, 0.40717173, 0.83885869, 0.22546008, 0.06415602,
       0.37193189, 0.4216578 , 0.03549723, 0.04318983, 0.03785214,
       0.02576588, 0.17224975, 0.34642356, 0.08965226, 0.31905683,
       0.47458377, 0.20865257, 0.6378511 , 0.76453856, 0.39293523,
       0.33812359, 0.6045046 , 0.02397444, 0.53541448, 0.32471215,
       0.92626463, 0.68567925, 0.54224965, 0.4825015 , 0.78459272,
       0.14423959, 0.03692861, 0.20024748, 0.14658394, 0.02200659,
       0.49471594, 0.84520267, 0.23750046, 0.39435745, 0.54190802,
       0.43298888, 0.68381991, 0.49370044, 0.07654426, 0.12921629,
       0.02575467, 0.01316481, 0.3485483 , 0.42054407, 0.29193588,
       0.67493308, 0.47655153, 0.04209806, 0.64766644, 0.66730725,
       0.11294667, 0.08546427, 0.1078433 , 0.19747427, 0.21445351,
       0.0446422 , 0.05889949, 0.04559882, 0.16171892, 0.14048696,
       0.04215549, 0.79774236, 0.4988231 , 0.77192753, 0.116607  ,
       0.11776643, 0.13464261, 0.6430494 , 0.31363198, 0.03960394,
       0.40811382, 0.09333301, 0.82746766, 0.45874712, 0.3121776 ,
       0.79542666, 0.48271892, 0.10837325, 0.13364843, 0.02487533,
       0.0286558 , 0.09712867, 0.41468411, 0.10287951, 0.46429078,
       0.15849402, 0.14142639, 0.48399003, 0.7479729 , 0.02866372,
       0.09245272, 0.02437566, 0.5534843 , 0.22554545, 0.52310194,
       0.93501867, 0.63381498, 0.17925867, 0.02940772, 0.04185764,
       0.03240004, 0.07920657, 0.40764423, 0.26034807, 0.03033317,
       0.77744932, 0.88738539, 0.03080322, 0.84512006, 0.45871505,
       0.05195818, 0.75348257, 0.12590122, 0.03048128, 0.47226254,
       0.02006813, 0.02596271, 0.45972057, 0.03766371, 0.06069969,
       0.77710994, 0.03351628, 0.12894949, 0.07439944, 0.03309626,
       0.02817388, 0.03668121, 0.3262381 , 0.49430486, 0.3726665 ,
       0.32446111, 0.04493247, 0.54957184, 0.31182017, 0.11374339,
       0.89655513, 0.16634749, 0.70885718, 0.23601149, 0.45110477,
       0.42850929, 0.04963987, 0.14888241, 0.85691028, 0.08279291,
       0.12604813, 0.03366274, 0.20405524, 0.04905544, 0.14902579,
       0.83635089, 0.02049371, 0.5764819 , 0.14697258, 0.62580914,
       0.32572668, 0.04547455, 0.16743898, 0.03941486, 0.43718821,
       0.12809376, 0.65897937, 0.12298083, 0.4159431 , 0.11640662,
       0.04646692, 0.07574639, 0.28848342, 0.95214486, 0.04240832,
       0.59222085, 0.81920232, 0.77961106, 0.12276951, 0.15856826,
       0.01715584, 0.756349  , 0.02935121, 0.05239621, 0.11073736,
       0.61690215, 0.86608955, 0.9022097 , 0.37742022, 0.81670774,
       0.26994332, 0.27101667, 0.05424589, 0.58700288, 0.05176834,
       0.15840428, 0.86512211, 0.17619305, 0.0687007 , 0.56391454,
       0.78956396, 0.02487741, 0.45957072, 0.03540213, 0.06345977,
       0.31947774, 0.39810148, 0.19566805, 0.05875911, 0.64873182,
       0.35918693, 0.0258521 , 0.81977146, 0.32952822, 0.24206805,
       0.16784743, 0.4152573 , 0.18041912, 0.56282648, 0.81050635,
       0.79657904, 0.0549007 , 0.73723778, 0.30947124, 0.69079335,
       0.5860184 , 0.19887334, 0.17287727, 0.12502576, 0.03376175,
       0.06287261, 0.16016688, 0.11332694, 0.27723778, 0.81044379,
       0.0277163 , 0.33134559, 0.12820694, 0.37839864, 0.48943396,
       0.04914005, 0.91281794, 0.09250575, 0.16220879, 0.83347619,
       0.17598457, 0.53755803, 0.07585637, 0.03802371, 0.68770978,
       0.71181853, 0.88712243, 0.06916631, 0.08065434, 0.05225049,
       0.02468792, 0.17113675, 0.54756536, 0.12045431, 0.07759084,
       0.39512444, 0.15432349, 0.75622727, 0.04309017, 0.43446655,
       0.18870635, 0.88164021, 0.13874457, 0.05602344, 0.14953849,
       0.02644794, 0.20482569, 0.02094615, 0.42487449, 0.02063941,
       0.60957025, 0.02288574, 0.6404963 , 0.07460024, 0.05253423,
       0.03799644, 0.58480398, 0.89434929, 0.02230247, 0.82891596,
       0.4004154 , 0.02410435, 0.45826629, 0.0165185 , 0.10919149,
       0.10069523, 0.75802858, 0.26965893, 0.0304043 , 0.05899866,
       0.04836235, 0.15356367, 0.41268666, 0.03104086, 0.86407191,
       0.75281574, 0.358201  , 0.32826339, 0.04311519, 0.32207374,
       0.06047844, 0.80506248, 0.56083887, 0.10266046, 0.76743097,
       0.49679363, 0.89547856, 0.68815591, 0.02293167, 0.05740071,
       0.50212691, 0.02218307, 0.36380581, 0.86985085, 0.8439776 ,
       0.19206573, 0.30870088, 0.0601541 , 0.02671934, 0.02859037,
       0.1598055 , 0.05740788, 0.56022042, 0.02912615, 0.84687943,
       0.38182527, 0.86575767, 0.16015094, 0.10090561, 0.32218092,
       0.55078035, 0.02802447, 0.41822295, 0.0709152 , 0.10222826,
       0.5257529 , 0.04594932, 0.57548194, 0.19151418, 0.64974954,
       0.1059667 , 0.5256909 , 0.27633427, 0.0585239 , 0.06007694,
       0.74865696, 0.37196832, 0.04163617, 0.60373627, 0.1381399 ,
       0.03353057, 0.05875546, 0.1396381 , 0.73906965, 0.44988105,
       0.78728403, 0.08139667, 0.02810642, 0.26704258, 0.72476277,
       0.07615405, 0.56183788, 0.58664493, 0.09060895, 0.10495381,
       0.80990663, 0.84353982, 0.77561258, 0.09855005, 0.05231055,
       0.22046279, 0.3407689 , 0.05911373, 0.10210042, 0.4532837 ,
       0.36233168, 0.72512403, 0.03338174, 0.02725841, 0.61927426,
       0.18641498, 0.4390984 , 0.3377739 , 0.9303893 , 0.04142901,
       0.03988377, 0.04653068, 0.25205295, 0.48917068, 0.87437316,
       0.5419421 , 0.21605477, 0.47940511, 0.44318347, 0.09750882,
       0.8321349 , 0.86645559, 0.0463962 , 0.53597927, 0.86594701,
       0.29509392, 0.91527646, 0.03488926, 0.02132232, 0.67771658,
       0.77378534, 0.22409762, 0.76913411, 0.85272988, 0.84180202,
       0.13288773, 0.1682783 , 0.40127413, 0.3676039 , 0.49109133,
       0.1278609 , 0.39705157, 0.79673775, 0.7882192 , 0.60012587,
       0.02482199, 0.29096679, 0.03102266, 0.85416169, 0.02943208,
       0.79030546, 0.05826534, 0.82488479, 0.4264532 , 0.33734613,
       0.33308534, 0.03235179, 0.89787402, 0.07912836, 0.8751446 ,
       0.39722279, 0.92692233, 0.11273582, 0.02527723, 0.93443249,
       0.5385837 , 0.43001163, 0.80202817, 0.88568467, 0.33758211,
       0.70615095, 0.04662966, 0.2581326 , 0.04852263, 0.72796766,
       0.72321139, 0.06394601, 0.0357237 , 0.76545217, 0.04999826,
       0.06371475, 0.13597958, 0.57089467, 0.41114091, 0.09234922,
       0.36366009, 0.72663164, 0.02782771, 0.02980994, 0.59114779,
       0.09290107, 0.21295718, 0.71495558, 0.44154298, 0.03452397,
       0.04003147, 0.05927486, 0.03759584, 0.82482679, 0.46990539,
       0.50104121, 0.88912985, 0.13123   , 0.52296431, 0.16152157,
       0.93286774, 0.8995262 , 0.3760115 , 0.0438943 , 0.06033776,
       0.37401867, 0.20350784, 0.05431757, 0.25716442, 0.03487835,
       0.10236273, 0.71551847, 0.37673911, 0.10747233, 0.29623284,
       0.84848938, 0.30586353, 0.04207574, 0.43219303, 0.86642845,
       0.03264959, 0.68654874, 0.16056339, 0.42737209, 0.04013483,
       0.822954  , 0.67503408, 0.3780244 , 0.04046953, 0.15011015,
       0.84946357, 0.30206795, 0.22027191, 0.43337557, 0.360653  ,
       0.34260995, 0.89341843, 0.62272985, 0.02505507, 0.53844074,
       0.06311199, 0.15447065, 0.1598514 , 0.11705941, 0.18101407,
       0.04790046, 0.51201976, 0.37854781, 0.55239801, 0.73681408,
       0.83870569, 0.13023151, 0.54486997, 0.76641949, 0.1379263 ,
       0.68706066, 0.02509173, 0.14793068, 0.866207  , 0.05245022,
       0.05634221, 0.82134796, 0.15620873, 0.84760777, 0.16646917,
       0.03989614, 0.26093916, 0.03077294, 0.3323905 , 0.70585202,
       0.54083985, 0.24263711, 0.83269925, 0.05171812, 0.78354182,
       0.0268433 , 0.2549827 , 0.22004105, 0.91404124, 0.05043926,
       0.08318872, 0.02779268, 0.41892881, 0.33917159, 0.10297027,
       0.81564242, 0.90142716, 0.60696569, 0.64713076, 0.46272782,
       0.24174097, 0.13531736, 0.54944031, 0.44267361, 0.02822936,
       0.92400042, 0.07408216, 0.097054  , 0.56016326, 0.58497791,
       0.2117687 , 0.04798192, 0.0605028 , 0.56567965, 0.07326411,
       0.06077279, 0.31035802, 0.41620593])

In binary classification, predict_proba() returns probabilities for both classes: column 0 is P(y=0) and column 1 is P(y=1). We usually extract [:,1] because metrics such as ROC-AUC, log loss, precision-recall analysis, and threshold tuning are defined using the probability of the positive class, which in this stroke problem is stroke = 1. The probability of class 0 is redundant because P(0) = 1 - P(1)

Model Prediction

In [67]:

log_reg.score(X_test_scaler,y_test)

0.7273838630806846

In [68]:
from sklearn.metrics import accuracy_score,classification_report

y_pred = log_reg.predict(X_test_scaler)
acc = accuracy_score(y_test, y_pred)
print(acc)

0.7273838630806846

In [69]:
y.value_counts()

stroke
0    3889
1     199
Name: count, dtype: int64

Model Evaluation:cost function

In [77]:

from sklearn.metrics import log_loss

# Calculate log loss
log_loss_value = log_loss(y_test, y_prob)
print(f"Log Loss : {log_loss_value:.4f}")

Log Loss : 0.5366

In [71]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.72      0.84       781
           1       0.12      0.81      0.21        37

    accuracy                           0.73       818
   macro avg       0.55      0.77      0.52       818
weighted avg       0.95      0.73      0.81       818

The balanced logistic regression model is able to detect most stroke cases (high recall = 0.81), which is desirable for a medical screening application. However, it produces many false positives (low precision = 0.12), leading to a reduction in overall accuracy to 73%. The log loss of 0.50 indicates that the predicted probabilities are reasonably calibrated and the model is not making many extremely overconfident errors.